### ISSUE TITLE
刚安装的hyperf-skeleton 在安装了hyperf/socketio-server组件后，运行了大概1分多钟后就报错误

### ISSUE THREAD

**Issue by 48021129** [hyperf/hyperf-skeleton#113]
错误内容：
[WARNING] Redis::__call failed, because read error on connection to localhost:6379
[ERROR] RedisException: read error on connection to localhost:6379 in /wwwroot/task/share.h-x.vip/test2/vendor/hyperf/redis/src/RedisConnection.php:211
Stack trace:
#0 /wwwroot/task/share.h-x.vip/test2/vendor/hyperf/redis/src/RedisConnection.php(211): Redis->subscribe()
#1 /wwwroot/task/share.h-x.vip/test2/vendor/hyperf/redis/src/RedisConnection.php(84): Hyperf\Redis\RedisConnection->retry()
#2 /wwwroot/task/share.h-x.vip/test2/vendor/hyperf/redis/src/Redis.php(43): Hyperf\Redis\RedisConnection->__call()
#3 /wwwroot/task/share.h-x.vip/test2/vendor/hyperf/socketio-server/src/Room/RedisAdapter.php(324): Hyperf\Redis\Redis->__call()
#4 /wwwroot/task/share.h-x.vip/test2/vendor/hyperf/socketio-server/src/Room/RedisAdapter.php(143): Hyperf\SocketIOServer\Room\RedisAdapter->phpRedisSubscribe()
#5 /wwwroot/task/share.h-x.vip/test2/vendor/hyperf/support/src/Functions.php(74): Hyperf\SocketIOServer\Room\RedisAdapter->Hyperf\SocketIOServer\Room\{closure}()
#6 /wwwroot/task/share.h-x.vip/test2/vendor/hyperf/socketio-server/src/Room/RedisAdapter.php(153): Hyperf\Support\retry()
#7 /wwwroot/task/share.h-x.vip/test2/vendor/hyperf/coroutine/src/Coroutine.php(79): Hyperf\SocketIOServer\Room\RedisAdapter->Hyperf\SocketIOServer\Room\{closure}()
#8 [internal function]: Hyperf\Coroutine\Coroutine::Hyperf\Coroutine\{closure}()
#9 {main}

环境信息：
Linux HXGZS.SERVER 3.10.0-1160.81.1.el7.x86_64 #1 SMP Fri Dec 16 17:29:43 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
PHP 8.1.27 (cli) (built: Jan  1 2024 12:21:43) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.27, Copyright (c) Zend Technologies
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Continue as root/super user [yes]? 
hyperf/cache                       v3.1.0  A cache component for hyperf.
hyperf/code-parser                 v3.1.4  A code parser component for Hyperf.
hyperf/codec                       v3.1.4  A codec component for Hyperf.
hyperf/collection                  v3.1.0  Hyperf Collection package which come from illuminate/collections
hyperf/command                     v3.1.2  Command for hyperf
hyperf/conditionable               v3.1.0  Hyperf Macroable package which come from illuminate/conditionable
hyperf/config                      v3.1.2  An independent component that provides configuration container.
hyperf/context                     v3.1.0  A coroutine/application context library.
hyperf/contract                    v3.1.2  The contracts of Hyperf.
hyperf/coordinator                 v3.1.0  Hyperf Coordinator
hyperf/coroutine                   v3.1.1  Hyperf Coroutine
hyperf/database                    v3.1.5  A flexible database library.
hyperf/db-connection               v3.1.5  A hyperf db connection handler for hyperf/database.
hyperf/devtool                     v3.1.5  A Devtool for Hyperf.
hyperf/di                          v3.1.2  A DI for Hyperf.
hyperf/dispatcher                  v3.1.0  A HTTP Server for Hyperf.
hyperf/engine                      v2.10.4 Coroutine engine provided by swoole.
hyperf/engine-contract             v1.9.1  Contract for Coroutine Engine
hyperf/event                       v3.1.0  an event manager that implements PSR-14.
hyperf/exception-handler           v3.1.5  Exception handler for hyperf
hyperf/framework                   v3.1.0  A coroutine framework that focuses on hyperspeed and flexible, specifically use for build microser...
hyperf/guzzle                      v3.1.0  Swoole coroutine handler for guzzle
hyperf/http-message                v3.1.0  microservice framework base on swoole
hyperf/http-server                 v3.1.0  A HTTP Server for Hyperf.
hyperf/logger                      v3.1.0  A logger component for hyperf.
hyperf/macroable                   v3.1.0  Hyperf Macroable package which come from illuminate/macroable
hyperf/memory                      v3.1.0  An independent component that use to operate and manage memory.
hyperf/model-listener              v3.1.0  A model listener for Hyperf.
hyperf/pipeline                    v3.1.0  Hyperf Macroable package which come from illuminate/pipeline
hyperf/pool                        v3.1.0  An independent universal connection pool component.
hyperf/process                     v3.1.0  A process component for hyperf.
hyperf/redis                       v3.1.0  A redis component for hyperf.
hyperf/serializer                  v3.1.0  A serializer component for Hyperf.
hyperf/server                      v3.1.2  A base server library for Hyperf.
hyperf/socketio-server             v3.1.1  Socket.io implementation for hyperf
hyperf/stdlib                      v3.1.0  A stdlib component for Hyperf.
hyperf/stringable                  v3.1.0  Hyperf Stringable package which come from illuminate/support
hyperf/support                     v3.1.0  A support component for Hyperf.
hyperf/tappable                    v3.1.0  Hyperf Macroable package which come from illuminate/tappable
hyperf/testing                     v3.1.3  Testing for hyperf
hyperf/utils                       v3.1.0  A tools package that could help developer solved the problem quickly.
hyperf/websocket-server            v3.1.0  A websocket server library for Hyperf.

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 5.0.1
Built => Jan 31 2023 17:17:23
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.0.2u  20 Dec 2019
http2 => enabled
json => enabled
pcre => enabled
zlib => 1.2.7
brotli => E16777225/D16777225
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608

重现方法:
composer create-project hyperf/hyperf-skeleton test
一路回车
cd test
composer require hyperf/websocket-server hyperf/socketio-server
先修改.env的redis配置
在server.php 中的servses中添加socket.io的配置，全部和官方文档中配置一样。
php bin/hyperf.php start

另一个老版本不会报错。不知道是不是最新骨架的哪个组件有问题？

**Comment by 48021129** [comment]
解决了
在redis配置中增加
'options' => [
    Redis::OPT_READ_TIMEOUT => -1,
]
