### ISSUE TITLE
rabbitmq使用报错

### ISSUE THREAD

**Issue by shuqingzai** [hyperf/hyperf-skeleton#52]
![image](https://user-images.githubusercontent.com/44406033/99945483-aa065300-2daf-11eb-849b-26ce610f35a9.png)
![image](https://user-images.githubusercontent.com/44406033/99946576-88a66680-2db1-11eb-8bc4-d8a8eec761ac.png)
### 错误信息
[ERROR] PhpAmqpLib\Exception\AMQPRuntimeException: Error sending data in /www/hy/code/vendor/hyperf/amqp/src/Connection/SwooleIO.php:198
Stack trace:
#0 /www/hy/code/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(388): Hyperf\Amqp\Connection\SwooleIO->write()
#1 /www/hy/code/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(516): PhpAmqpLib\Connection\AbstractConnection->write()
#2 /www/hy/code/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(247): PhpAmqpLib\Connection\AbstractConnection->send_channel_method_frame()
#3 /www/hy/code/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(724): PhpAmqpLib\Channel\AbstractChannel->send_method_frame()
#4 /www/hy/code/vendor/hyperf/amqp/src/Connection.php(144): PhpAmqpLib\Connection\AbstractConnection->close()
#5 /www/hy/code/vendor/hyperf/pool/src/Pool.php(87): Hyperf\Amqp\Connection->close()
#6 /www/hy/code/vendor/hyperf/pool/src/Pool.php(68): Hyperf\Pool\Pool->flush()
#7 /www/hy/code/vendor/hyperf/amqp/src/Producer.php(36): Hyperf\Pool\Pool->get()
#8 /www/hy/code/vendor/hyperf/amqp/src/Producer.php(23): Hyperf\Amqp\Producer->produceMessage()
#9 /www/hy/code/vendor/hyperf/utils/src/Functions.php(79): Hyperf\Amqp\Producer->Hyperf\Amqp\{closure}()
#10 /www/hy/code/vendor/hyperf/amqp/src/Producer.php(24): retry()
#11 /www/hy/code/app/Crontab/AdminSync.php(50): Hyperf\Amqp\Producer->produce()
#12 /www/hy/code/vendor/hyperf/utils/src/Functions.php(270): App\Crontab\AdminSync->App\Crontab\{closure}()
#13 /www/hy/code/vendor/hyperf/utils/src/Coroutine.php(71): call()
#14 {main}

#### 定时器执行的内容
    public function execute()
    {
        $data         = [
            'method' => time(),
            'time'   => date('Y-m-d H:i:s')
        ];
        $amqpProducer = $this->container->get(Producer::class);
        for ($i = 1; $i <= 10; $i++) {
            $data['key'] = $i;
            go(function () use ($data, $amqpProducer) {
                $message = new AdminProducer($data);

                $amqpProducer->produce($message);
            });
        }
    }

**Comment by limingxinleo** [comment]
composer info | grep hyperf
