### ISSUE TITLE
使用composer创建3.x.x版本无法运行，运行就会报异常类不存在

### ISSUE THREAD

**Issue by seanhepps** [hyperf/hyperf-skeleton#88]
```
/data/project/articlerobot # php bin/hyperf.php start
PHP Warning:  Class "Hyperf\Coroutine\Exception\ChannelClosedException" not found in /data/project/articlerobot/vendor/hyperf/utils/src/Exception/ChannelClosedException.php on line 14

Warning: Class "Hyperf\Coroutine\Exception\ChannelClosedException" not found in /data/project/articlerobot/vendor/hyperf/utils/src/Exception/ChannelClosedException.php on line 14
PHP Fatal error:  Uncaught Error: Class "Hyperf\Coroutine\Exception\ChannelClosedException" not found in /data/project/articlerobot/vendor/hyperf/utils/src/Exception/ChannelClosedException.php:20
Stack trace:
#0 /data/project/articlerobot/vendor/composer/ClassLoader.php(582): include()
#1 /data/project/articlerobot/vendor/composer/ClassLoader.php(433): Composer\Autoload\{closure}()
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#3 /data/project/articlerobot/vendor/hyperf/utils/src/Functions.php(541): class_exists()
#4 /data/project/articlerobot/vendor/composer/autoload_real.php(41): require('...')
#5 /data/project/articlerobot/vendor/composer/autoload_real.php(45): {closure}()
#6 /data/project/articlerobot/vendor/autoload.php(25): ComposerAutoloaderInit0f5b3b520d3f47f6cf86a63c8937b99c::getLoader()
#7 /data/project/articlerobot/bin/hyperf.php(14): require('...')
#8 {main}
  thrown in /data/project/articlerobot/vendor/hyperf/utils/src/Exception/ChannelClosedException.php on line 20

Fatal error: Uncaught Error: Class "Hyperf\Coroutine\Exception\ChannelClosedException" not found in /data/project/articlerobot/vendor/hyperf/utils/src/Exception/ChannelClosedException.php:20
Stack trace:
#0 /data/project/articlerobot/vendor/composer/ClassLoader.php(582): include()
#1 /data/project/articlerobot/vendor/composer/ClassLoader.php(433): Composer\Autoload\{closure}()
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#3 /data/project/articlerobot/vendor/hyperf/utils/src/Functions.php(541): class_exists()
#4 /data/project/articlerobot/vendor/composer/autoload_real.php(41): require('...')
#5 /data/project/articlerobot/vendor/composer/autoload_real.php(45): {closure}()
#6 /data/project/articlerobot/vendor/autoload.php(25): ComposerAutoloaderInit0f5b3b520d3f47f6cf86a63c8937b99c::getLoader()
#7 /data/project/articlerobot/bin/hyperf.php(14): require('...')
#8 {main}
  thrown in /data/project/articlerobot/vendor/hyperf/utils/src/Exception/ChannelClosedException.php on line 20
```

**Comment by limingxinleo** [comment]
https://mp.weixin.qq.com/s/SxpfXRGMG2akancFX98YVg

看一下这个，创建完后，然后加一下 代理，再重新 composer update -oW
